export enum ActionTypes {
  ADD_TODO = 'ADD_TODO',
  TOGGLE_TODO = 'TOGGLE_TODO',
  REMOVE_TODO = 'REMOVE_TODO',

  FETCH_COLORS_REQUEST = 'FETCH_COLORS_REQUEST',
  FETCH_COLORS_SUCCESS = 'FETCH_COLORS_SUCCESS',
  FETCH_COLORS_FAILURE = 'FETCH_COLORS_FAILURE',
}

export default ActionTypes;
